Q_IMPORT_PLUGIN(Detail);
Q_IMPORT_PLUGIN(DetailFooter);
Q_IMPORT_PLUGIN(DetailHeader);
Q_IMPORT_PLUGIN(Overlay);
Q_IMPORT_PLUGIN(PageFooter);
Q_IMPORT_PLUGIN(PageHeader);
Q_IMPORT_PLUGIN(Summary);
Q_IMPORT_PLUGIN(Title);

Q_IMPORT_PLUGIN(Page);
Q_IMPORT_PLUGIN(Printer);
Q_IMPORT_PLUGIN(Renderer);
Q_IMPORT_PLUGIN(Script);

Q_IMPORT_PLUGIN(CsvDataset);
Q_IMPORT_PLUGIN(FileSystemDataset);
Q_IMPORT_PLUGIN(ModelDataset);
Q_IMPORT_PLUGIN(SqlDataset);

Q_IMPORT_PLUGIN(ExportPDF);
//Q_IMPORT_PLUGIN(ExportSVG);

Q_IMPORT_PLUGIN(ArcItem);
#ifdef GPL
Q_IMPORT_PLUGIN(BarcodeItem);
#endif
//Q_IMPORT_PLUGIN(Chart);
Q_IMPORT_PLUGIN(ChordItem);
Q_IMPORT_PLUGIN(EllipseItem);
Q_IMPORT_PLUGIN(ImageItem);
Q_IMPORT_PLUGIN(LineItem);
Q_IMPORT_PLUGIN(MemoItem);
Q_IMPORT_PLUGIN(PieItem);
Q_IMPORT_PLUGIN(RectangleItem);

Q_IMPORT_PLUGIN(SerializerXML);

Q_IMPORT_PLUGIN(StorageFileSystem);
Q_IMPORT_PLUGIN(StorageGit);
Q_IMPORT_PLUGIN(StorageResource);
Q_IMPORT_PLUGIN(StorageSql);
